apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "factorychat.fullname" . }}-settingsconfig
  labels:
    app: {{ template "factorychat.fullname" . }}
    chart: {{ template "factorychat.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
{{ toJson .Values.configSettings | indent 4 }}