{{ if not .Values.persistence.dataDir.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "factorychat.fullname" . }}-datadir
  labels:
    app: "{{ template "factorychat.fullname" . }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dataDir.Size | quote }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{ end }}