
# Number of replicas to create (only 1 is supported)
replicaCount: 1

image:
  repository: "coreysabia/factorychatbot"
  # Container image pull policy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# Security options the operator container should run with
securityContext:
  runAsUser: 1000
  fsGroup: 2000

service:
  type: LoadBalancer
  port: 30000

# Compute Resources required by the operator container
resources: # +doc-gen:break
  requests:
    memory: 512Mi
    cpu: 500m
# Node labels for pod assignment
# Example:
# nodeSelector:  
#  beta.kubernetes.io/os: linux
#  beta.kubernetes.io/arch: amd64
nodeSelector: {} # +doc-gen:break

# Tolerations for pod assignment
tolerations: []

# Affinity rules for pod assignment
affinity: {}

# Sets the data persistence volume configuration
persistence:
  dataDir: 
    Size: "20Gi"
    existingClaim: pvc-factorio
  storageClass: longhorn

setConf:
  config_path: /opt/factorio-bot

configSettings:
  logFile: "/factorio/Factorio-server.log"
  chatChannel: "YOUR_CHANNEL_ID"
  cleanMessages: "false"
  consoleChannel: "false"
  logLines: "true"

  startupMessage:
    enabled: "True"
    messages: "This Factorio Chat Bot is running in Kubernetes inside Sam's ass!"

  RconIP: "10.10.10.42"
  RconPort: "27015"
  RconPassword: "YOUR_RCON_PASS"
  token: "YOUR_DISCORD_TOKEN"

#console logging for discord chat bot
# ARGS for additional arguments to be passed to the server execution
#arguments: [
#    "--console-log,", 
#    "/opt/factorio/Factorio-server.log,",
#]
